// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type {
  getHealthzData,
  getHealthzResponses,
  postWebhooksTransactionNotifyData,
  postWebhooksTransactionNotifyErrors,
  postWebhooksTransactionNotifyResponses,
} from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<
  TData,
  ThrowOnError
> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: Record<string, unknown>;
};

/**
 * Check the health status of the service
 */
export const getHealthz = <ThrowOnError extends boolean = false>(options?: Options<getHealthzData, ThrowOnError>) =>
  (options?.client ?? client).get<getHealthzResponses, unknown, ThrowOnError>({ url: '/healthz', ...options });

/**
 * Notify transaction
 */
export const postWebhooksTransactionNotify = <ThrowOnError extends boolean = false>(
  options: Options<postWebhooksTransactionNotifyData, ThrowOnError>,
) =>
  (options.client ?? client).post<
    postWebhooksTransactionNotifyResponses,
    postWebhooksTransactionNotifyErrors,
    ThrowOnError
  >({
    url: '/webhooks/transaction-notify',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
