// This file is auto-generated by @hey-api/openapi-ts

export enum TransactionType {
  CHANGE_HANDLE = 'CHANGE_HANDLE',
  CREATE_HANDLE = 'CREATE_HANDLE',
  SIWF_SIGNUP = 'SIWF_SIGNUP',
  SIWF_SIGNIN = 'SIWF_SIGNIN',
  ADD_KEY = 'ADD_KEY',
  RETIRE_MSA = 'RETIRE_MSA',
  ADD_PUBLIC_KEY_AGREEMENT = 'ADD_PUBLIC_KEY_AGREEMENT',
  REVOKE_DELEGATION = 'REVOKE_DELEGATION',
  CAPACITY_BATCH = 'CAPACITY_BATCH',
}

export type TxWebhookRspBase = {
  blockHash: string;
  providerId: string;
  referenceId: string;
  msaId: string;
  transactionType: TransactionType;
  txHash: string;
};

export type PublishHandleOpts = {
  handle: string;
};

export type SIWFOpts = {
  handle: string;
  accountId: string;
};

export type PublishKeysOpts = {
  newPublicKey: string;
};

export type PublishGraphKeysOpts = {
  schemaId: string;
};

export type CapacityBatchAllOpts = {
  calls: Array<{
    section: string;
    method: string;
  }>;
  capacityWithdrawnEvent: {
    msaId: string;
    amount: string;
  };
};

export type TxWebhookOpts =
  | PublishHandleOpts
  | SIWFOpts
  | PublishKeysOpts
  | PublishGraphKeysOpts
  | CapacityBatchAllOpts;

export type PublishHandleWebhookRsp = TxWebhookRspBase &
  PublishHandleOpts & {
    transactionType: 'CREATE_HANDLE' | 'CHANGE_HANDLE';
  };

export type SIWFWebhookRsp = TxWebhookRspBase &
  SIWFOpts & {
    transactionType: 'SIWF_SIGNUP';
  };

export type PublishKeysWebhookRsp = TxWebhookRspBase &
  PublishKeysOpts & {
    transactionType: 'ADD_KEY';
  };

export type PublishGraphKeysWebhookRsp = TxWebhookRspBase &
  PublishGraphKeysOpts & {
    transactionType: 'ADD_PUBLIC_KEY_AGREEMENT';
  };

export type RetireMsaWebhookRsp = TxWebhookRspBase & {
  transactionType: 'RETIRE_MSA';
};

export type RevokeDelegationWebhookRsp = TxWebhookRspBase & {
  transactionType: 'REVOKE_DELEGATION';
};

export type CapacityBatchAllWebhookRsp = TxWebhookRspBase &
  CapacityBatchAllOpts & {
    transactionType: 'CAPACITY_BATCH';
  };

export type TxWebhookRsp =
  | ({
      transactionType?: 'PublishHandleWebhookRsp';
    } & PublishHandleWebhookRsp)
  | ({
      transactionType?: 'SIWFWebhookRsp';
    } & SIWFWebhookRsp)
  | ({
      transactionType?: 'PublishKeysWebhookRsp';
    } & PublishKeysWebhookRsp)
  | ({
      transactionType?: 'PublishGraphKeysWebhookRsp';
    } & PublishGraphKeysWebhookRsp)
  | ({
      transactionType?: 'RetireMsaWebhookRsp';
    } & RetireMsaWebhookRsp)
  | ({
      transactionType?: 'RevokeDelegationWebhookRsp';
    } & RevokeDelegationWebhookRsp)
  | ({
      transactionType?: 'CapacityBatchAllWebhookRsp';
    } & CapacityBatchAllWebhookRsp);

export type GetHealthz_Data = {
  body?: never;
  path?: never;
  query?: never;
  url: '/healthz';
};

export type GetHealthz_Responses = {
  /**
   * Service is healthy
   */
  200: unknown;
};

export type PostTransactionNotify_Data = {
  body: TxWebhookRsp;
  path?: never;
  query?: never;
  url: '/transaction-notify';
};

export type PostTransactionNotify_Errors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type PostTransactionNotify_Responses = {
  /**
   * Successful notification
   */
  200: unknown;
};

export type ClientOptions = {
  baseUrl: `${string}://openapi-specs` | (string & {});
};
