---
#
# Define webhook API for the Frequency Developer Gateway Account Service. The nestjs/swagger package does not
# support auto-generation of webhooks, or types that are not part of controller
# endpoints.
#
# Also, note we use the 'paths:' component here, not the new 'webhooks:' component supported
# by OpenAPI >= 3.1. This is because the documentation generators do not yet fully support webhooks.
openapi: 3.1.0
info:
  title: Transaction Notification API
  version: 1.0.0

paths:
  /healthz:
    get:
      responses:
        '200':
          description: 'Service is healthy'
      summary: 'Check the health status of the service'

  /webhooks/transaction-notify:
    post:
      summary: Notify transaction
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TxWebhookRsp'
      responses:
        '200':
          description: Successful notification
        '400':
          description: Bad request

components:
  schemas:
    TransactionType:
      type: string
      enum:
        - CHANGE_HANDLE
        - CREATE_HANDLE
        - SIWF_SIGNUP
        - SIWF_SIGNIN
        - ADD_KEY
        - RETIRE_MSA
        - ADD_PUBLIC_KEY_AGREEMENT
        - REVOKE_DELEGATION
        - CAPACITY_BATCH
      x-enum-varnames:
        - CHANGE_HANDLE
        - CREATE_HANDLE
        - SIWF_SIGNUP
        - SIWF_SIGNIN
        - ADD_KEY
        - RETIRE_MSA
        - ADD_PUBLIC_KEY_AGREEMENT
        - REVOKE_DELEGATION
        - CAPACITY_BATCH

    TxWebhookRspBase:
      type: object
      optional:
        - msaId
      required:
        - blockHash
        - providerId
        - referenceId
        - txHash
      properties:
        blockHash:
          type: string
        providerId:
          type: string
        referenceId:
          type: string
        msaId:
          type: string
        txHash:
          type: string

    PublishHandleOpts:
      type: object
      properties:
        handle:
          type: string
      required:
        - handle

    SIWFOpts:
      type: object
      properties:
        handle:
          type: string
        accountId:
          type: string
      required:
        - handle
        - accountId

    PublishKeysOpts:
      type: object
      properties:
        newPublicKey:
          type: string
      required:
        - newPublicKey

    PublishGraphKeysOpts:
      type: object
      properties:
        schemaId:
          type: string
      required:
        - schemaId

    CapacityBatchAllOpts:
      type: object
      properties:
        calls:
          type: array
          items:
            type: object
            properties:
              section:
                type: string
              method:
                type: string
            required:
              - section
              - method
        capacityWithdrawnEvent:
          type: object
          properties:
            msaId:
              type: string
            amount:
              type: string
          required:
            - amount
            - msaId
      required:
        - calls
        - capacityWithdrawnEvent

    TxWebhookOpts:
      type: object
      oneOf:
        - $ref: '#/components/schemas/PublishHandleOpts'
        - $ref: '#/components/schemas/SIWFOpts'
        - $ref: '#/components/schemas/PublishKeysOpts'
        - $ref: '#/components/schemas/PublishGraphKeysOpts'
        - $ref: '#/components/schemas/CapacityBatchAllOpts'

    CreateHandleWebhookRsp:
      type: object
      allOf:
        - $ref: '#/components/schemas/TxWebhookRspBase'
        - $ref: '#/components/schemas/PublishHandleOpts'
        - type: object
          properties:
            transactionType:
              type: string
              enum:
                - CREATE_HANDLE
          required:
            - transactionType

    ChangeHandleWebhookRsp:
      type: object
      allOf:
        - $ref: '#/components/schemas/TxWebhookRspBase'
        - $ref: '#/components/schemas/PublishHandleOpts'
        - type: object
          properties:
            transactionType:
              type: string
              enum:
                - CHANGE_HANDLE
          required:
            - transactionType

    PublishHandleWebhookRsp:
      type: object
      oneOf:
        - $ref: '#/components/schemas/CreateHandleWebhookRsp'
        - $ref: '#/components/schemas/ChangeHandleWebhookRsp'

    SIWFWebhookRsp:
      type: object
      allOf:
        - $ref: '#/components/schemas/TxWebhookRspBase'
        - $ref: '#/components/schemas/SIWFOpts'
        - type: object
          properties:
            transactionType:
              type: string
              enum:
                - SIWF_SIGNUP
          required:
            - transactionType

    PublishKeysWebhookRsp:
      type: object
      allOf:
        - $ref: '#/components/schemas/TxWebhookRspBase'
        - $ref: '#/components/schemas/PublishKeysOpts'
        - type: object
          properties:
            transactionType:
              type: string
              enum:
                - ADD_KEY
          required:
            - transactionType

    PublishGraphKeysWebhookRsp:
      type: object
      allOf:
        - $ref: '#/components/schemas/TxWebhookRspBase'
        - $ref: '#/components/schemas/PublishGraphKeysOpts'
        - type: object
          properties:
            transactionType:
              type: string
              enum:
                - ADD_PUBLIC_KEY_AGREEMENT
          required:
            - transactionType

    RetireMsaWebhookRsp:
      type: object
      allOf:
        - $ref: '#/components/schemas/TxWebhookRspBase'
        - type: object
          properties:
            transactionType:
              type: string
              enum:
                - RETIRE_MSA
          required:
            - transactionType

    RevokeDelegationWebhookRsp:
      type: object
      allOf:
        - $ref: '#/components/schemas/TxWebhookRspBase'
        - type: object
          properties:
            transactionType:
              type: string
              enum:
                - REVOKE_DELEGATION
          required:
            - transactionType

    CapacityBatchAllWebhookRsp:
      type: object
      allOf:
        - $ref: '#/components/schemas/TxWebhookRspBase'
        - $ref: '#/components/schemas/CapacityBatchAllOpts'
        - type: object
          properties:
            transactionType:
              type: string
              enum:
                - CAPACITY_BATCH
          required:
            - transactionType

    TxWebhookRsp:
      discriminator:
        propertyName: transactionType
        mapping:
          CREATE_HANDLE: '#/components/schemas/CreateHandleWebhookRsp'
          CHANGE_HANDLE: '#/components/schemas/ChangeHandleWebhookRsp'
          SIWF_SIGNUP: '#/components/schemas/SIWFWebhookRsp'
          ADD_KEY: '#/components/schemas/PublishKeysWebhookRsp'
          ADD_PUBLIC_KEY_AGREEMENT: '#/components/schemas/PublishGraphKeysWebhookRsp'
          RETIRE_MSA: '#/components/schemas/RetireMsaWebhookRsp'
          REVOKE_DELEGATION: '#/components/schemas/RevokeDelegationWebhookRsp'
          CAPACITY_BATCH: '#/components/schemas/CapacityBatchAllWebhookRsp'
      oneOf:
        - $ref: '#/components/schemas/CreateHandleWebhookRsp'
        - $ref: '#/components/schemas/ChangeHandleWebhookRsp'
        - $ref: '#/components/schemas/SIWFWebhookRsp'
        - $ref: '#/components/schemas/PublishKeysWebhookRsp'
        - $ref: '#/components/schemas/PublishGraphKeysWebhookRsp'
        - $ref: '#/components/schemas/RetireMsaWebhookRsp'
        - $ref: '#/components/schemas/RevokeDelegationWebhookRsp'
        - $ref: '#/components/schemas/CapacityBatchAllWebhookRsp'
