# Default values for frequency-gateway.
# Declare variables to be passed into your templates.

# This will set the replicaset count
replicaCount: 1

# Container image details
image:
  repository: nginx
  pullPolicy: IfNotPresent
  tag: ""

# Image pull secrets for private registry
imagePullSecrets: []

# Chart name overrides
nameOverride: ""
fullnameOverride: ""

# Service account configuration
serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

# Pod annotations and labels
podAnnotations: {}
podLabels: {}

# Pod and container security contexts
podSecurityContext: {}
securityContext: {}

# Service configuration
service:
  type: ClusterIP
  port: 80

# Ingress configuration
ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

# Resource limits and requests
resources: {}

# Liveness and readiness probes
livenessProbe:
  httpGet:
    path: /
    port: http
readinessProbe:
  httpGet:
    path: /
    port: http

# Autoscaling configuration
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

# Additional volumes and volume mounts
volumes: []
volumeMounts: []

# Node selector, tolerations, and affinity settings
nodeSelector: {}
tolerations: []
affinity: {}

# Environment variables for the gateway applications and workers
account:
  image:
    repository: "projectlibertylabs/gateway"
    tag: "latest"
  env:
    API_PORT: "3001"
    FREQUENCY_URL: "ws://0.0.0.0:9944"
    FREQUENCY_HTTP_URL: "http://0.0.0.0:9944"
    PROVIDER_ID: "1"
    WEBHOOK_BASE_URL: "http://host.docker.internal:3001/webhooks/account-service"
    REDIS_URL: "redis://0.0.0.0:6379"
    BLOCKCHAIN_SCAN_INTERVAL_SECONDS: "3"
    TRUST_UNFINALIZED_BLOCKS: "true"
    WEBHOOK_FAILURE_THRESHOLD: "3"
    WEBHOOK_RETRY_INTERVAL_SECONDS: "10"
    HEALTH_CHECK_MAX_RETRIES: "4"
    HEALTH_CHECK_MAX_RETRY_INTERVAL_SECONDS: "10"
    HEALTH_CHECK_SUCCESS_THRESHOLD: "10"
    CAPACITY_LIMIT: '{"serviceLimit":{"type":"percentage","value":"80"}}'
    SIWF_URL: "https://ProjectLibertyLabs.github.io/siwf/ui"
    SIWF_DOMAIN: "localhost"
    DEBUG: "true"
    CACHE_KEY_PREFIX: "account:"
    GRAPH_ENVIRONMENT_TYPE: "TestnetPaseo"
    API_TIMEOUT_MS: "5000"
    API_BODY_JSON_LIMIT: "1mb"
  secret:
    PROVIDER_ACCESS_TOKEN: "some-token"
    PROVIDER_ACCOUNT_SEED_PHRASE: "'//Alice'"

contentPublishing:
  env:
    API_PORT: "3001"
    BLOCKCHAIN_SCAN_INTERVAL_SECONDS: "12"
    TRUST_UNFINALIZED_BLOCKS: "false"
    IPFS_ENDPOINT: "http://127.0.0.1:5001"
    IPFS_GATEWAY_URL: "http://127.0.0.1:8080/ipfs/[CID]"
    FREQUENCY_URL: "ws://0.0.0.0:9944"
    PROVIDER_ID: "1"
    REDIS_URL: "redis://0.0.0.0:6379"
    CAPACITY_LIMIT: '{"serviceLimit":{"type":"percentage","value":"80"}}'
    FILE_UPLOAD_MAX_SIZE_IN_BYTES: "2000000000"
    ASSET_EXPIRATION_INTERVAL_SECONDS: "300"
    BATCH_INTERVAL_SECONDS: "12"
    BATCH_MAX_COUNT: "1000"
    ASSET_UPLOAD_VERIFICATION_DELAY_SECONDS: "5"
    CACHE_KEY_PREFIX: "content-publishing:"
  secret:
    IPFS_BASIC_AUTH_USER: ""
    IPFS_BASIC_AUTH_SECRET: ""
    PROVIDER_ACCOUNT_SEED_PHRASE: "'//Alice'"

contentWatcher:
  env:
    API_PORT: "3002"
    IPFS_ENDPOINT: "http://127.0.0.1:5001"
    IPFS_GATEWAY_URL: "http://127.0.0.1:8080/ipfs/[CID]"
    FREQUENCY_URL: "ws://0.0.0.0:9944"
    REDIS_URL: "redis://0.0.0.0:6379"
    BLOCKCHAIN_SCAN_INTERVAL_SECONDS: "12"
    QUEUE_HIGH_WATER: "1000"
    WEBHOOK_FAILURE_THRESHOLD: "4"
    WEBHOOK_RETRY_INTERVAL_SECONDS: "10"
    CACHE_KEY_PREFIX: "content-watcher:"
  secret:
    IPFS_BASIC_AUTH_USER: ""
    IPFS_BASIC_AUTH_SECRET: ""

graph:
  env:
    API_PORT: "3003"
    FREQUENCY_URL: "ws://0.0.0.0:9944"
    PROVIDER_ID: "1"
    REDIS_URL: "redis://0.0.0.0:6379"
    QUEUE_HIGH_WATER: "1000"
    DEBOUNCE_SECONDS: "10"
    CAPACITY_LIMIT: '{"serviceLimit":{"type":"percentage","value":"80"}}'
    GRAPH_ENVIRONMENT_TYPE: "Mainnet"
    RECONNECTION_SERVICE_REQUIRED: "true"
    PROVIDER_BASE_URL: "https://some-provider/api/v1.0.0"
    CONNECTIONS_PER_PROVIDER_RESPONSE_PAGE: "100"
    BLOCKCHAIN_SCAN_INTERVAL_SECONDS: "6"
    WEBHOOK_FAILURE_THRESHOLD: "3"
    HEALTH_CHECK_SUCCESS_THRESHOLD: "10"
    WEBHOOK_RETRY_INTERVAL_SECONDS: "10"
    HEALTH_CHECK_MAX_RETRY_INTERVAL_SECONDS: "10"
    HEALTH_CHECK_MAX_RETRIES: "4"
    CACHE_KEY_PREFIX: "graph:"
  secret:
    PROVIDER_ACCOUNT_SEED_PHRASE: "'//Ferdie'"
    PROVIDER_ACCESS_TOKEN: "some-token"
