name: 'Install mdBook with Plugins'
description: 'Shared action steps to install mdBook with required plugins'
inputs:
  token:
    description: 'Pass through for secrets.GITHUB_TOKEN'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Setup mdBook 📚
      uses: jontze/action-mdbook@6c0be56d14c4bf16861b00af61f50ff7400ce502
      with:
        token: ${{ inputs.token }}
        mdbook-version: '0.4.51' # Use a semver compatible string
        # Optional Plugins have to be enabled
        # use-linkcheck: true
        # linkcheck-version: "~0.7.7"
        # add mdbook-mermaid plugin
        use-mermaid: true
        mermaid-version: '0.15.0'

    - name: Show mdbook version
      shell: bash
      run: mdbook --version
    - name: Show mdbook-mermaid version
      shell: bash
      run: mdbook-mermaid --version
    # - name: Show linkchecker version
    #   shell: bash
    #   run: mdbook-linkcheck --version
