/* eslint-disable import/no-unresolved */
/* eslint-disable func-names */
/*
 * Account Service
 * Account Service API
 *
 * OpenAPI spec version: 1.0
 *
 * NOTE: This class is auto generated by OpenAPI Generator.
 * https://github.com/OpenAPITools/openapi-generator
 *
 * Generator version: 7.7.0-SNAPSHOT
 */

import http from 'k6/http';
import { group, check, sleep } from 'k6';

export const options = {
  // scenarios: {
  //   constant_request_rate: {
  //     executor: 'constant-arrival-rate',
  //     rate: 1000,
  //     timeUnit: '1s',
  //     duration: '10s',
  //     preAllocatedVUs: 100,
  //     maxVUs: 200,
  //   },
  // },
  vus: 1,
  duration: '20s',
  thresholds: {
    http_req_duration: ['avg<100', 'p(95)<200'],
  },
  noConnectionReuse: true,
  // stages: [
  //   { duration: '30s', target: 10 }, // Ramp-up to 10 users over 30 seconds
  //   { duration: '1m', target: 10 }, // Stay at 10 users for 1 minute
  //   { duration: '30s', target: 0 }, // Ramp-down to 0 users over 30 seconds
  // ],
};

const CALLBACK_URL = 'http://localhost:3001/webhooks/account-service';
const BASE_URL = 'http://localhost:3000';
// Sleep duration between successive requests.
const SLEEP_DURATION = 0.1;
const BLOCKTIME_SECONDS = 12;
// Global variables should be initialized.

function checkCallback() {
  const res = http.get(CALLBACK_URL);
  console.log('Callback response:', res.status, res.body);
  check(res, {
    'callback received': (r) => r.status === 201,
    'callback contains expected data': (r) => {
      const json = JSON.parse(r.body);
      return json.referenceId === 'DekKx1F_WYOWCQFXE3vgwqXP4U4';
    },
  });
}

export function setup() {
  // Let's make sure the service is healthy before starting the test.
  console.log('Checking service health...');
  const res = http.get(`${BASE_URL}/api/health`);
  console.log('Service health check status:', res.status);
  if (res.status !== 200) {
    console.error('Service is not healthy! Terminating test...');
    return false;
  }
  return true;
}

export default function () {
  group('/accounts/siwf', () => {
    // Request No. 1: AccountsController_getSIWFConfig
    {
      const url = `${BASE_URL}/accounts/siwf`;
      const request = http.get(url);

      check(request, {
        'Returned SIWF Configuration data': (r) => r.status === 200,
      });

      sleep(SLEEP_DURATION);
    }

    // Request No. 2: AccountsController_postSignInWithFrequency
    {
      const url = `${BASE_URL}/accounts/siwf`;
      // Use the SIWF sample Sign Up request body for a new user.
      const body = {
        signUp: {
          extrinsics: [
            {
              pallet: 'msa',
              extrinsicName: 'createSponsoredAccountWithDelegation',
              encodedExtrinsic:
                '0xed01043c01b01b4dcafc8a8e73bff98e7558249f53cd0e0e64fa6b8f0159f0913d4874d9360176644186458bad3b00bbd0ac21e6c9bd5a8bed9ced7a772d11a9aac025b47f6559468808e272696f596a02af230951861027c0dc30f7163ecf316838a0723483010000000000000014000000000000000000004d000000',
            },
            {
              pallet: 'handles',
              extrinsicName: 'claimHandle',
              encodedExtrinsic:
                '0xb901044200b01b4dcafc8a8e73bff98e7558249f53cd0e0e64fa6b8f0159f0913d4874d93601225508ae2da9804c60660a150277eb32b2a0f6b9c8f6e07dd6cad799cb31ae1dfb43896f488e9c0b7ec8b530d930b3f9b690683f2765d5def3fee3fc6540d58714656e6464794d000000',
            },
          ],
        },
      };
      const params = { headers: { 'Content-Type': 'application/json', Accept: 'application/json' } };
      const request = http.post(url, JSON.stringify(body), params);

      check(request, {
        'Signed in successfully': (r) => r.status === 201,
      });
    }

    // The front end will poll the server for the account status.
    // We'll wait here for a block to be finalized.
    sleep(BLOCKTIME_SECONDS);
    console.log('Block finalized. Checking callback...');
    checkCallback();
  });
}
