FROM node:22

WORKDIR /app

# Create a non-root user
RUN groupadd -g 1001 nodejs && \
    useradd -u 1001 -g nodejs -s /bin/bash -m gateway

RUN mkdir -p /app/node_modules && \
    chown -R gateway:nodejs /app && \
    chmod -R 775 /app

RUN echo "umask 002" >> /home/gateway/.bashrc && \
    echo "umask 002" >> /etc/profile

USER 1001

EXPOSE 3000

HEALTHCHECK --interval=60s --timeout=10s --start-period=30s --retries=3 \
    CMD curl -f http://localhost:3000/livez || exit 1

VOLUME [ "/app" ]
