// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

export enum TransactionType {
  /**
   * CAPACITY_BATCH
   */
  CAPACITY_BATCH = 'CAPACITY_BATCH',
  /**
   * ON_CHAIN_CONTENT
   */
  ON_CHAIN_CONTENT = 'ON_CHAIN_CONTENT',
  /**
   * CHANGE_HANDLE
   */
  CHANGE_HANDLE = 'CHANGE_HANDLE',
  /**
   * CREATE_HANDLE
   */
  CREATE_HANDLE = 'CREATE_HANDLE',
  /**
   * SIWF_SIGNUP
   */
  SIWF_SIGNUP = 'SIWF_SIGNUP',
  /**
   * SIWF_SIGNIN
   */
  SIWF_SIGNIN = 'SIWF_SIGNIN',
  /**
   * ADD_KEY
   */
  ADD_KEY = 'ADD_KEY',
  /**
   * RETIRE_MSA
   */
  RETIRE_MSA = 'RETIRE_MSA',
  /**
   * ADD_PUBLIC_KEY_AGREEMENT
   */
  ADD_PUBLIC_KEY_AGREEMENT = 'ADD_PUBLIC_KEY_AGREEMENT',
  /**
   * REVOKE_DELEGATION
   */
  REVOKE_DELEGATION = 'REVOKE_DELEGATION',
  /**
   * CAPACITY_BATCH
   */
  CAPACITY_BATCH2 = 'CAPACITY_BATCH',
}

export type TxWebhookRspBase = {
  blockHash: string;
  providerId: string;
  referenceId: string;
  msaId?: string;
  txHash: string;
};

export type OnChainContentOpts = {
  msaId: string;
  intentId: string;
  schemaId: string;
};

export type PublishHandleOpts = {
  handle: string;
};

export type SIWFOpts = {
  handle: string;
  accountId: string;
};

export type PublishKeysOpts = {
  newPublicKey: string;
};

export type PublishGraphKeysOpts = {
  schemaId: string;
};

export type CapacityBatchAllOpts = {
  calls: Array<{
    section: string;
    method: string;
  }>;
  capacityWithdrawnEvent: {
    msaId: string;
    amount: string;
  };
};

export type TxWebhookOpts =
  | OnChainContentOpts
  | PublishHandleOpts
  | SIWFOpts
  | PublishKeysOpts
  | PublishGraphKeysOpts
  | CapacityBatchAllOpts;

export type CreateHandleWebhookRsp = TxWebhookRspBase &
  PublishHandleOpts & {
    transactionType: 'CREATE_HANDLE';
  };

export type OnChainContentRsp = TxWebhookRspBase &
  OnChainContentOpts & {
    transactionType: 'ON_CHAIN_ONTENT';
  };

export type ChangeHandleWebhookRsp = TxWebhookRspBase &
  PublishHandleOpts & {
    transactionType: 'CHANGE_HANDLE';
  };

export type PublishHandleWebhookRsp = CreateHandleWebhookRsp | ChangeHandleWebhookRsp;

export type SIWFWebhookRsp = TxWebhookRspBase &
  SIWFOpts & {
    transactionType: 'SIWF_SIGNUP';
  };

export type PublishKeysWebhookRsp = TxWebhookRspBase &
  PublishKeysOpts & {
    transactionType: 'ADD_KEY';
  };

export type PublishGraphKeysWebhookRsp = TxWebhookRspBase &
  PublishGraphKeysOpts & {
    transactionType: 'ADD_PUBLIC_KEY_AGREEMENT';
  };

export type RetireMsaWebhookRsp = TxWebhookRspBase & {
  transactionType: 'RETIRE_MSA';
};

export type RevokeDelegationWebhookRsp = TxWebhookRspBase & {
  transactionType: 'REVOKE_DELEGATION';
};

export type CapacityBatchAllWebhookRsp = TxWebhookRspBase &
  CapacityBatchAllOpts & {
    transactionType: 'CAPACITY_BATCH';
  };

export type TxWebhookRsp =
  | ({
      transactionType: 'ON_CHAIN_ONTENT';
    } & OnChainContentRsp)
  | ({
      transactionType: 'CREATE_HANDLE';
    } & CreateHandleWebhookRsp)
  | ({
      transactionType: 'CHANGE_HANDLE';
    } & ChangeHandleWebhookRsp)
  | ({
      transactionType: 'SIWF_SIGNUP';
    } & SIWFWebhookRsp)
  | ({
      transactionType: 'ADD_KEY';
    } & PublishKeysWebhookRsp)
  | ({
      transactionType: 'ADD_PUBLIC_KEY_AGREEMENT';
    } & PublishGraphKeysWebhookRsp)
  | ({
      transactionType: 'RETIRE_MSA';
    } & RetireMsaWebhookRsp)
  | ({
      transactionType: 'REVOKE_DELEGATION';
    } & RevokeDelegationWebhookRsp)
  | ({
      transactionType: 'CAPACITY_BATCH';
    } & CapacityBatchAllWebhookRsp);

export type getHealthzData = {
  body?: never;
  path?: never;
  query?: never;
  url: '/healthz';
};

export type getHealthzResponses = {
  /**
   * Service is healthy
   */
  200: unknown;
};

export type postWebhooksTransactionNotifyData = {
  body: TxWebhookRsp;
  path?: never;
  query?: never;
  url: '/webhooks/transaction-notify';
};

export type postWebhooksTransactionNotifyErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type postWebhooksTransactionNotifyResponses = {
  /**
   * Successful notification
   */
  200: unknown;
};
