---
#
# Define webhook API for Graph Service. The nestjs/swagger package does not
# support auto-generation of webhooks, or types that are not part of controller
# endpoints.
# These interface types at inception match the interfaces exported by @dsnp/graph-sdk
openapi: 3.1.0
info:
  title: Graph Service Webhooks API
  version: 1.0.0
webhooks:
  graph-update:
    post:
      summary: Announce a graph update
      operationId: announceGraphUpdateV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/GraphChangeNotificationV1'
      responses:
        '200':
          description: Graph update announcement handled
        '400':
          description: Bad request
  graph-request-status:
    post:
      summary: Send the status of a requested graph update
      operationId: updateOperationStatusV1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              '$ref': '#/components/schemas/GraphOperationStatusV1'
      responses:
        '200':
          description: Graph operation status received
        '400':
          description: Bad request
components:
  schemas:
    GraphChangeNotificationV1:
      type: object
      properties:
        msaId:
          type: string
          description: MSA Id for which this notification is being sent
          example: '2'
        schemaId:
          type: number
          description: Schema ID of graph that was updated
          example: 8
        pageId:
          type: number
          description: Page ID of graph page that was updated/deleted
          example: 15
        prevContentHash:
          type: number
          description: integer representation of the content hash of the updated page's previous state
          example: 123456
        currContentHash:
          type: number
          description: integer representation of the content hash of the updated pages new state
        updateType:
          title: updateType
          enum:
            - GraphPageUpdated
            - GraphPageDeleted
      required:
        - msaId
        - schemaId
        - pageId
        - prevContentHash
        - updateType
    GraphOperationStatusV1:
      type: object
      properties:
        referenceId:
          type: string
          description: Job reference ID of a previously submitted graph update request
          example: 'Lve95gjOVATpfV8EL5X4nxwjKHE'
        status:
          title: status
          enum:
            - pending
            - expired
            - failed
            - succeeded
          type: string
      required:
        - referenceId
        - status
