{{- if not .Values.vault.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: account-secret
type: Opaque
data:
  PROVIDER_ACCESS_TOKEN: {{ .Values.account.secret.PROVIDER_ACCESS_TOKEN | b64enc | quote }}
  PROVIDER_ACCOUNT_SEED_PHRASE: {{ .Values.account.secret.PROVIDER_ACCOUNT_SEED_PHRASE | b64enc | quote }}

{{- end }}
