apiVersion: v1
kind: ConfigMap
metadata:
  name: content-publishing-configmap
data:
  BLOCKCHAIN_SCAN_INTERVAL_SECONDS: "{{ .Values.contentPublishing.env.BLOCKCHAIN_SCAN_INTERVAL_SECONDS }}"
  TRUST_UNFINALIZED_BLOCKS: "{{ .Values.contentPublishing.env.TRUST_UNFINALIZED_BLOCKS }}"
  IPFS_ENDPOINT: "{{ .Values.contentPublishing.env.IPFS_ENDPOINT }}"
  IPFS_GATEWAY_URL: "{{ .Values.contentPublishing.env.IPFS_GATEWAY_URL }}"
  FREQUENCY_URL: "{{ .Values.contentPublishing.env.FREQUENCY_URL }}"
  PROVIDER_ID: "{{ .Values.contentPublishing.env.PROVIDER_ID }}"
  REDIS_URL: "{{ .Values.contentPublishing.env.REDIS_URL }}"
  CAPACITY_LIMIT: "{{ .Values.contentPublishing.env.CAPACITY_LIMIT }}"
  API_PORT: "{{ .Values.contentPublishing.env.API_PORT }}"
  FILE_UPLOAD_MAX_SIZE_IN_BYTES: "{{ .Values.contentPublishing.env.FILE_UPLOAD_MAX_SIZE_IN_BYTES }}"
  ASSET_EXPIRATION_INTERVAL_SECONDS: "{{ .Values.contentPublishing.env.ASSET_EXPIRATION_INTERVAL_SECONDS }}"
  BATCH_INTERVAL_SECONDS: "{{ .Values.contentPublishing.env.BATCH_INTERVAL_SECONDS }}"
  BATCH_MAX_COUNT: "{{ .Values.contentPublishing.env.BATCH_MAX_COUNT }}"
  ASSET_UPLOAD_VERIFICATION_DELAY_SECONDS: "{{ .Values.contentPublishing.env.ASSET_UPLOAD_VERIFICATION_DELAY_SECONDS }}"
  CACHE_KEY_PREFIX: "{{ .Values.contentPublishing.env.CACHE_KEY_PREFIX }}"
