{{- if not .Values.vault.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: content-watcher-secret
type: Opaque
data:
  IPFS_BASIC_AUTH_USER: {{ .Values.contentWatcher.secret.IPFS_BASIC_AUTH_USER | b64enc | quote }}
  IPFS_BASIC_AUTH_SECRET: {{ .Values.contentWatcher.secret.IPFS_BASIC_AUTH_SECRET | b64enc | quote }}

{{- end }}
