{{- if not .Values.vault.enabled }}

apiVersion: v1
kind: Secret
metadata:
  name: content-publishing-secret
type: Opaque
data:
  IPFS_BASIC_AUTH_USER: {{ .Values.contentPublishing.secret.IPFS_BASIC_AUTH_USER | b64enc | quote }}
  IPFS_BASIC_AUTH_SECRET: {{ .Values.contentPublishing.secret.IPFS_BASIC_AUTH_SECRET | b64enc | quote }}
  PROVIDER_ACCOUNT_SEED_PHRASE: {{ .Values.contentPublishing.secret.PROVIDER_ACCOUNT_SEED_PHRASE | b64enc | quote }}

{{- end }}
