{{- if .Values.vault.enabled }}

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: account-secret
spec:
  backendType: vault
  vault:
    server: "{{ .Values.vault.address }}"
    path: "{{ .Values.vault.secretsPath }}/account"
    version: "v2"
    auth:
      tokenSecretRef:
        name: "{{ .Values.vault.tokenSecretName }}"
        key: "{{ .Values.vault.tokenSecretKey }}"

  data:
    - key: PROVIDER_ACCESS_TOKEN
      name: PROVIDER_ACCESS_TOKEN
    - key: PROVIDER_ACCOUNT_SEED_PHRASE
      name: PROVIDER_ACCOUNT_SEED_PHRASE

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: content-publishing-secret
spec:
  backendType: vault
  vault:
    server: "{{ .Values.vault.address }}"
    path: "{{ .Values.vault.secretsPath }}/content-publishing"
    version: "v2"
    auth:
      tokenSecretRef:
        name: "{{ .Values.vault.tokenSecretName }}"
        key: "{{ .Values.vault.tokenSecretKey }}"

  data:
    - key: IPFS_BASIC_AUTH_USER
      name: IPFS_BASIC_AUTH_USER
    - key: IPFS_BASIC_AUTH_SECRET
      name: IPFS_BASIC_AUTH_SECRET
    - key: PROVIDER_ACCOUNT_SEED_PHRASE
      name: PROVIDER_ACCOUNT_SEED_PHRASE

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: content-watcher-secret
spec:
  backendType: vault
  vault:
    server: "{{ .Values.vault.address }}"
    path: "{{ .Values.vault.secretsPath }}/content-watcher"
    version: "v2"
    auth:
      tokenSecretRef:
        name: "{{ .Values.vault.tokenSecretName }}"
        key: "{{ .Values.vault.tokenSecretKey }}"

  data:
    - key: IPFS_BASIC_AUTH_USER
      name: IPFS_BASIC_AUTH_USER
    - key: IPFS_BASIC_AUTH_SECRET
      name: IPFS_BASIC_AUTH_SECRET

---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: graph-secret
spec:
  backendType: vault
  vault:
    server: "{{ .Values.vault.address }}"
    path: "{{ .Values.vault.secretsPath }}/graph"
    version: "v2"
    auth:
      tokenSecretRef:
        name: "{{ .Values.vault.tokenSecretName }}"
        key: "{{ .Values.vault.tokenSecretKey }}"

  data:
    - key: PROVIDER_ACCOUNT_SEED_PHRASE
      name: PROVIDER_ACCOUNT_SEED_PHRASE
    - key: PROVIDER_ACCESS_TOKEN
      name: PROVIDER_ACCESS_TOKEN

{{- end }}
