apiVersion: v1
kind: ConfigMap
metadata:
  name: graph-configmap
data:
  API_PORT: {{ .Values.graph.env.API_PORT | quote }}
  FREQUENCY_API_WS_URL: {{ .Values.graph.env.FREQUENCY_API_WS_URL | quote }}
  PROVIDER_ID: {{ .Values.graph.env.PROVIDER_ID | quote }}
  REDIS_OPTIONS: {{ .Values.graph.env.REDIS_OPTIONS | quote }}
  REDIS_URL: {{ .Values.graph.env.REDIS_URL | quote }}
  QUEUE_HIGH_WATER: {{ .Values.graph.env.QUEUE_HIGH_WATER | quote }}
  DEBOUNCE_SECONDS: {{ .Values.graph.env.DEBOUNCE_SECONDS | quote }}
  CAPACITY_LIMIT: {{ .Values.graph.env.CAPACITY_LIMIT | quote }}
  GRAPH_ENVIRONMENT_TYPE: {{ .Values.graph.env.GRAPH_ENVIRONMENT_TYPE | quote }}
  RECONNECTION_SERVICE_REQUIRED: {{ .Values.graph.env.RECONNECTION_SERVICE_REQUIRED | quote }}
  PROVIDER_BASE_URL: {{ .Values.graph.env.PROVIDER_BASE_URL | quote }}
  CONNECTIONS_PER_PROVIDER_RESPONSE_PAGE: {{ .Values.graph.env.CONNECTIONS_PER_PROVIDER_RESPONSE_PAGE | quote }}
  BLOCKCHAIN_SCAN_INTERVAL_SECONDS: {{ .Values.graph.env.BLOCKCHAIN_SCAN_INTERVAL_SECONDS | quote }}
  WEBHOOK_FAILURE_THRESHOLD: {{ .Values.graph.env.WEBHOOK_FAILURE_THRESHOLD | quote }}
  HEALTH_CHECK_SUCCESS_THRESHOLD: {{ .Values.graph.env.HEALTH_CHECK_SUCCESS_THRESHOLD | quote }}
  WEBHOOK_RETRY_INTERVAL_SECONDS: {{ .Values.graph.env.WEBHOOK_RETRY_INTERVAL_SECONDS | quote }}
  HEALTH_CHECK_MAX_RETRY_INTERVAL_SECONDS: {{ .Values.graph.env.HEALTH_CHECK_MAX_RETRY_INTERVAL_SECONDS | quote }}
  HEALTH_CHECK_MAX_RETRIES: {{ .Values.graph.env.HEALTH_CHECK_MAX_RETRIES | quote }}
  CACHE_KEY_PREFIX: {{ .Values.graph.env.CACHE_KEY_PREFIX | quote }}
