apiVersion: v1
kind: Secret
metadata:
  name: graph-secret
type: Opaque
data:
  PROVIDER_ACCOUNT_SEED_PHRASE: {{ .Values.vault.enabled | ternary "'vault:/frequency-gateway/graph/PROVIDER_ACCOUNT_SEED_PHRASE'" (.Values.graph.secret.PROVIDER_ACCOUNT_SEED_PHRASE | b64enc | quote) }}
  PROVIDER_ACCESS_TOKEN: {{ .Values.vault.enabled | ternary "'vault:/frequency-gateway/graph/PROVIDER_ACCESS_TOKEN'" (.Values.graph.secret.PROVIDER_ACCESS_TOKEN | b64enc | quote) }}
