{{- if .Values.vault.enabled }}
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
spec:
  provider:
    vault:
      server: "{{ .Values.vault.address }}"
      path: "{{ .Values.vault.secretsPath }}"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "{{ .Values.vault.tokenSecretName }}"
          key: "{{ .Values.vault.tokenSecretKey }}"
{{- end }}
