// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
  baseURL: `${string}://${string}` | (string & {});
};

export enum AnnouncementType {
  /**
   * Tombstone
   */
  Tombstone = 0,
  /**
   * Broadcast
   */
  Broadcast = 2,
  /**
   * Reply
   */
  Reply = 3,
  /**
   * Reaction
   */
  Reaction = 4,
  /**
   * Profile
   */
  Profile = 5,
  /**
   * Update
   */
  Update = 6,
}

export type AnnouncementResponse = {
  /**
   * An optional identifier for the request, may be used for tracking or correlation
   */
  requestId?: string;
  /**
   * An optional webhook URL registered as part of a specific search request
   */
  webhookUrl?: string;
  /**
   * Identifier for the schema being used or referenced
   */
  schemaId: number;
  /**
   * The block number on the blockchain where this announcement was recorded
   */
  blockNumber: number;
  announcement:
    | TombstoneAnnouncement
    | BroadcastAnnouncement
    | ReplyAnnouncement
    | ReactionAnnouncement
    | ProfileAnnouncement
    | UpdateAnnouncement;
};

export type TypedAnnouncement = {
  announcementType: AnnouncementType;
  fromId: string;
};

export type TombstoneAnnouncement = TypedAnnouncement & {
  announcementType?: AnnouncementType.Tombstone;
  targetAnnouncementType: number;
  targetContentHash: string;
};

export type BroadcastAnnouncement = TypedAnnouncement & {
  announcementType?: AnnouncementType.Broadcast;
  contentHash: string;
  url: string;
};

export type ReplyAnnouncement = TypedAnnouncement & {
  announcementType?: AnnouncementType.Reply;
  contentHash: string;
  inReplyTo: string;
  url: string;
};

export type ReactionAnnouncement = TypedAnnouncement & {
  announcementType?: AnnouncementType.Reaction;
  emoji: string;
  inReplyTo: string;
  apply: number;
};

export type ProfileAnnouncement = TypedAnnouncement & {
  announcementType?: AnnouncementType.Profile;
  contentHash: string;
  url: string;
};

export type UpdateAnnouncement = TypedAnnouncement & {
  announcementType?: AnnouncementType.Update;
  contentHash: string;
  targetAnnouncementType: number;
  targetContentHash: string;
  url: string;
};

export type createAnnouncementResponseData = {
  body: AnnouncementResponse;
  path?: never;
  query?: never;
  url: '/content-announcements';
};

export type createAnnouncementResponseErrors = {
  /**
   * Bad request
   */
  400: unknown;
};

export type createAnnouncementResponseResponses = {
  /**
   * Content announcement notification received
   */
  201: unknown;
};
