// eslint-disable-next-line no-shadow
export enum TransactionType {
  CHANGE_HANDLE = 'CHANGE_HANDLE',
  CREATE_HANDLE = 'CREATE_HANDLE',
  SIWF_SIGNUP = 'SIWF_SIGNUP',
  SIWF_SIGNIN = 'SIWF_SIGNIN',
  ADD_KEY = 'ADD_KEY',
  ADD_PUBLIC_KEY_AGREEMENT = 'ADD_PUBLIC_KEY_AGREEMENT',
  REVOKE_DELEGATION = 'REVOKE_DELEGATION',
}
