[book]
authors = ["Project Liberty Labs"]
language = "en"
src = "src"
title = "Frequency Developer Gateway"

[preprocessor.button-links]
command = "node preprocessors/button-links.mjs"

[preprocessor.svg-embed]
command = "node preprocessors/svg-embed.mjs"

[preprocessor.swagger-embed]
command = "node preprocessors/swagger-embed.mjs"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.tailwind]
renderers = ["html"]
command = 'node preprocessors/noop-npx.mjs "npx -y @tailwindcss/cli -i ./theme/tailwind.css -o ./css/tailwind.css"'

[output.html]
additional-css = [
  "css/tailwind.css",
  "css/overrides.css",
  "css/side-nav.css",
  "css/button-links.css",
  "css/highlight.css",
  "css/highlight-dark.css",
]
no-section-label = true
copy-fonts = false # Switched to custom fonts
git-repository-url = "https://github.com/ProjectLibertyLabs/gateway"
edit-url-template = "https://github.com/ProjectLibertyLabs/gateway/blob/main/docs/src/{path}"
preferred-dark-theme = "coal"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
