[book]
authors = ["Project Liberty Labs"]
language = "en"
multilingual = false
src = "src"
title = "Frequency Developer Gateway"

[preprocessor.button-links]
command = "node preprocessors/button-links.mjs"

[preprocessor.svg-embed]
command = "node preprocessors/svg-embed.mjs"

[preprocessor.swagger-embed]
command = "node preprocessors/swagger-embed.mjs"


[output.html]
additional-css = [
  "css/extended.css",
  "css/highlight.css",
  "css/highlight-dark.css",
]
no-section-label = true
git-repository-url = "https://github.com/ProjectLibertyLabs/gateway"
edit-url-template = "https://github.com/ProjectLibertyLabs/gateway/blob/main/docs/src/{path}"
preferred-dark-theme = "coal"

[output.html.fold]
enable = true
