[book]
authors = ["Project Liberty Labs"]
language = "en"
src = "src"
title = "Frequency Developer Gateway"

[preprocessor.button-links]
command = "node preprocessors/button-links.mjs"

[preprocessor.svg-embed]
command = "node preprocessors/svg-embed.mjs"

[preprocessor.swagger-embed]
command = "node preprocessors/swagger-embed.mjs"

[preprocessor.mermaid]
command = "mdbook-mermaid"

[output.html]
additional-css = [
  "css/highlight.css",
  "css/highlight-dark.css",
  "css/tailwind-short.css",
  "css/button-links.css",
  "css/overrides.css",
]
no-section-label = true
git-repository-url = "https://github.com/ProjectLibertyLabs/gateway"
edit-url-template = "https://github.com/ProjectLibertyLabs/gateway/blob/main/docs/src/{path}"
preferred-dark-theme = "coal"
additional-js = ["mermaid.min.js", "mermaid-init.js"]

[output.html.fold]
enable = true
